version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./:/app

  db:
    image: postgres:15.3-alpine3.17
    restart: always
    env_file:
      - .env

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - db
